# Generated by Django 3.1.1 on 2020-09-26 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='habit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit'),
        ),
    ]
