# Generated by Django 3.1.1 on 2020-09-26 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_event_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.habit'),
        ),
    ]
