# Generated by Django 3.1.1 on 2020-09-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0010_habit_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.CharField(default=' - ', max_length=1024),
        ),
    ]
