# Generated by Django 3.1.1 on 2020-09-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0011_auto_20200926_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
