name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: psycopg2 prerequisites
      run: sudo apt-get install python-dev libpq-dev

    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1

    - name: Install dependencies
      run: |
        pipenv install --dev

    - name: Run migrations
      run: pipenv run python manage.py migrate

    - name: Run Tests
      env:
        PSQL_NAME: postgres
        PSQL_USER: postgres
        PSQL_PASSWORD: postgres
        PSQL_PORT: ${{ job.services.postgres.ports[5432] }}
      run: |
        pipenv run python manage.py test
