name: Create production PR

on:
  push:
    branches:
      - master

jobs:
  createPR:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "master"
          destination_branch: "production"
          pr_title: "Production Deploy"
          pr_body: ":crown: An automated PR"
          pr_label: "production-deploy"
          pr_allow_empty: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
